export const GET_ALL_ARTICLE = 'GET_ALL_ARTICLE';
export const SET_ALL_ARTICLE = 'SET_ALL_ARTICLE';
export const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK';
export const SET_ALL_BOOKMARK = 'SET_ALL_BOOKMARK';